### PR TITLE
Add graphite support

### PR DESCRIPTION
**Pull request by rabunkosar-dd**

### CODE REVIEW

**Review by sebastianyates — APPROVED** [review]

**Comment by rabunkosar-dd** [comment]
@josephgee @JSchuenke @mmichael mind taking a look at this PR? thank you very much

**Review by laullon — APPROVED** [review]
LGTM

**Comment by laullon** [comment]
@mmichael can you take a look?

**Review by mmichael — APPROVED** [review]

**Comment by rabunkosar-dd** [comment]
@mmichael mind merging this? thanks!

**Comment by josephgee** [comment]
Sorry, @rabunkosar-dd. Most of the people you've tagged are on the collector team and aren't involved enough with the proxy to make sure this gets validated correctly. We're trying to find someone to follow through with this.

**Pull request closed without merging**
