### PR TITLE
Support Apiserver with custom domain

### PR DESCRIPTION
**Pull request by frederiko**
This PR simply removes the default `cluster.local` domain. Apiserver metrics are not able to be scrape when `collector.apiServerMetrics` is set to true running on a custom Kubernetes cluster domain.

### CODE REVIEW

**Comment by frederiko** [comment]
Is there anyone to review this pr?

**Comment by frederiko** [comment]
Hi @mmichael Do you think you or someone could help with reviewing this PR? THanks!

**Comment by josephgee** [comment]
Hi @frederiko! We've added validating this to our backlog. Its a bit more manual than we'd like at the moment, so its not the next thing up, but I didn't want you to know that we weren't ignoring you. :)

**Comment by frederiko** [comment]
Hi @josephgee , I really appreciate your comment and getting back to me. I do use use this chart and realized this potential issue a while back. Please let me know if I can be of any help.

**Comment by frederiko** [comment]
@josephgee Friendly ping. Is there any update on this PR? Thanks ;-)

**Review by helen-shao — APPROVED** [review]

**Comment by helen-shao** [comment]
Hi @frederiko, we merged your PR in and it will be included in our next helm chart release.

**Comment by frederiko** [comment]
Thank you @helen-shao . I will keep an eye for the next release.

**Pull request merged**
